---
- ansible.builtin.stat:
    path: '{{ gtk_installed_exe }}'
  become: true
  changed_when: false
  name: Check for installation at {{ gtk_install_exe }}
  register: gtk_binary
- always:
    - name: Rm {{ gtk_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ gtk_tmp_tgz }}'
        state: absent
  block:
    - ansible.builtin.get_url:
        url: '{{ gtk_url }}'
        dest: '{{ gtk_tmp_tgz }}'
        checksum: '{{ gtk_checksum }}'
        mode: '644'
      become: true
      become_user: root
      name: download {{ gtk_url }}...
    - ansible.builtin.file:
        path: '{{ gtk_install_dir }}'
        state: directory
        mode: '755'
      become: true
      become_user: root
      name: Mkdir {{ gtk_install_dir }}
    - ansible.builtin.unarchive:
        remote_src: true
        src: '{{ gtk_tmp_tgz }}'
        dest: '{{ gtk_install_dir }}'
        creates: '{{ gtk_installed_exe }}'
      become: true
      become_user: root
      name: Unarchive {{ gtk_tmp_tgz }}
  when: not gtk_binary.stat.exists
- ansible.builtin.file:
    src: '{{ gtk_installed_exe }}'
    dest: '{{ gtk_installed_link }}'
    state: link
  become: true
  become_user: root
  name: Link {{ gtk_installed_link }} to {{ gtk_installed_exe }}
