---
- name: Install dependent binaries
  block:
    - name: Install unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Install git
      ansible.builtin.include_role:
        name: andrewrothstein.git
    - name: Install kubectl
      ansible.builtin.include_role:
        name: andrewrothstein.kubectl
    - name: Install k3d
      ansible.builtin.include_role:
        name: andrewrothstein.kind
    - name: Install argocd cli
      ansible.builtin.include_role:
        name: andrewrothstein.argocd
  when: gtk_install_dependent_binaries | default(true)

- ansible.builtin.include_tasks: install_gtk.yml
  name: Install gitops-toolkit cli

- ansible.builtin.include_tasks: install_cacert.yml
  name: Install CA cert bundle
  when: _gtk_ca.enabled

- ansible.builtin.git:
    repo: '{{ _gtk_argocd.git.repo }}'
    version: '{{ _gtk_argocd.git.version }}'
    dest: '{{ _gtk_argocd.git.local_dir }}'
  name: >-
    Cloning argocd deployment manifest from
    {{ _gtk_argocd.git.repo }}@{{ _gtk_argocd.git.version }}
    to {{ _gtk_argocd.git.local_dir }}
  when: _gtk_argocd.git.enabled

- name: Generating {{ _gtk_clusters_template.dest }}...
  ansible.builtin.template:
    src: '{{ _gtk_clusters_template.j2 }}'
    dest: '{{ _gtk_clusters_template.dest }}'
    mode: '644'
  become: true
  become_user: root

- name: Starting clusters...
  ansible.builtin.include_tasks: start_clusters.yml
  when: _gtk_start_clusters.enabled
