---
- name: andrewrothstein.unarchivedeps
  version: 3.0.0
- name: andrewrothstein.git
  version: v3.2.8
- name: andrewrothstein.kubectl
  version: v1.2.13
- name: andrewrothstein.argocd
  version: v1.2.3
- name: andrewrothstein.k3d
  version: v1.1.9
